### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingualpress.pro#11]
Include a language switcher for all translation, there we have in the `language` folder. The default is a rewrite to the browser language, but the last chance is the language switcher.

 @glueckpress On which position?

**Comment by glueckpress** [comment]
Note to self: http://translate.marketpress.com/projects/multilingualpress.pro-site

**Comment by glueckpress** [comment]
Status: working on switch, will look like this.

![bildschirmfoto 2015-10-11 um 00 49 21](https://cloud.githubusercontent.com/assets/308422/10418693/bcc82190-7062-11e5-8c6d-c242e0046452.png)

**Comment by glueckpress** [comment]
Implemented `current-language` state. (Notice URL changing.)

**Light box-shadow for `current-language` link on mobile:**

![mlp pro-current-lang--mobile](https://cloud.githubusercontent.com/assets/308422/10480029/2f4ddc1c-7268-11e5-8a91-3365f156b46f.gif)

**Slightly darker background for `current-language` link on desktop:**

![mlp pro-current-lang--desktop](https://cloud.githubusercontent.com/assets/308422/10480039/36a0d942-7268-11e5-946e-faf3e9bc7afa.gif)

**Comment by bueltge** [comment]
:bouquet:
